### PR TITLE
Build and push updated operator on PR merge

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by JaydipGabani** [comment]
@jmontleon can you update the version to `latest` [here](https://github.com/konveyor/mtrho-operator/blob/main/config/manager/manager.yaml#L34) as well?

**Comment by jmontleon** [comment]
> @jmontleon can you update the version to `latest` [here](https://github.com/konveyor/mtrho-operator/blob/main/config/manager/manager.yaml#L34) as well?

Updated!

**Comment by jmontleon** [comment]
Actually, give me a minute. I think I can test.

**Comment by jmontleon** [comment]
Should be very close: https://github.com/jmontleon/mtrho-operator/runs/5742350037?check_suite_focus=true

**Review by JaydipGabani — APPROVED** [review]
LGTM

**Review by djzager — APPROVED** [review]

**Pull request merged**
